# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- releases/*

pool:
  vmImage: 'ubuntu-latest'

variables:

  APIGEE_ORG: "bap-emea-apigee-5"
  APIGEE_CONFIG_ENV: "configurable-dev"
  TEST_HOST: 34-117-38-184.nip.io

  # GCP_SERVICE_ACCOUNT is stored in Azure Pipeline variable settings
  
steps:


# install node.js tools and dependencies
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  enabled: "true"
    
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
  displayName: npmInstalls
  enabled: "true"



# Generate GCP Service Account file from Azure Pipeline variable GCP_SERVICE_ACCOUNT
# if deploy to Apigee X/hybrid
- bash: |
    echo '$(GCP_SERVICE_ACCOUNT)' > sa.json
  enabled: "true"
  condition:  eq(variables.API_VERSION, 'googleapi')
  displayName: Generate SA Key file 
  env:  
    GCP_SERVICE_ACCOUNT: $(GCP_SERVICE_ACCOUNT)

- task: CmdLine@2
  inputs:
    script: |
      gcloud auth activate-service-account \
          --quiet \
          --key-file sa.json && \
      gcloud components install beta && \
      gcloud beta apigee archives deploy --organization=$APIGEE_ORG \
          --environment=$APIGEE_CONFIG_ENV --source=proxy

# run Apickli, API test integration
- bash: |
    echo "run Apickli"
    mkdir integration_output
    export NODE_TLS_REJECT_UNAUTHORIZED="0"
    sed -i "s/organization_hostname/$TEST_HOST/g" ./test/integration/features/support/init.js
    node ./node_modules/cucumber/bin/cucumber-js ./test/integration --format json:report.json
    node ./test/integration/index.js
    cp ./cucumber_report.html integration_output/apickli_report.html 
  displayName: runApickli
  enabled: "false"

  

# Publish integration test folder result
- task: PublishBuildArtifacts@1
  displayName: publishInteegrationTestsResults
  enabled: "false"
  inputs:
    pathToPublish: integration_output
    artifactName: integration-tests


