# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- releases/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  APIGEE_ORG: "bap-emea-apigee-5"
  APIGEE_CONFIG_ENV: "configurable-dev"
  TEST_HOST: 34-117-38-184.nip.io

  # GCP_SERVICE_ACCOUNT is stored in Azure Pipeline variable settings
  
steps:

# install node.js tools and dependencies
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  enabled: "true"
    
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
  displayName: npmInstalls
  enabled: "true"

# Generate GCP Service Account file from Azure Pipeline variable GCP_SERVICE_ACCOUNT
# if deploy to Apigee X/hybrid
- bash: |
    echo '$(GCP_SERVICE_ACCOUNT)' > sa.json
  enabled: "true"
  displayName: Generate SA Key file 
  env:  
    GCP_SERVICE_ACCOUNT: $(GCP_SERVICE_ACCOUNT)

- task: CmdLine@2
  inputs:
    script: |
      # Configure local repo
      mv ./proxy/src/main/apigee/environments/ENVIRONMENT-NAME ./proxy/src/main/apigee/environments/$APIGEE_CONFIG_ENV
      gcloud auth activate-service-account \
          --quiet \
          --key-file sa.json && \
      echo "Deploying Configurable proxy (archive)..."
      gcloud beta apigee archives deploy --organization=$APIGEE_ORG \
          --environment=$APIGEE_CONFIG_ENV --source=proxy

# run Apickli, API test integration
- bash: |
    echo "Running Apickli..."
    # extract basepath from proxy config file
    API_BASEPATH=$(grep 'basepath:' ./proxy/src/main/apigee/apiproxies/hipster-conf/config.yaml | tail -n1 | awk '{ print $2}' | sed 's,/,\\/,g' | tr -d '"')
      
    # extract proxy name from folder structure
    PROXY_NAME=$(ls ./proxy/src/main/apigee/apiproxies/)
        
    # update apickli config file (init.js) with API hostname and base path
    sed -i "s/api_basepath/$API_BASEPATH/g" ./test/$PROXY_NAME/integration/features/support/init.js
    sed -i "s/organization_hostname/$TEST_HOST/g" ./test/$PROXY_NAME/integration/features/support/init.js
    
    # NODE_TLS_REJECT_UNAUTHORIZED required to support self signed certificate
    export NODE_TLS_REJECT_UNAUTHORIZED=0
    
    node ./node_modules/.bin/cucumber-js  ./test/$PROXY_NAME/integration --format json:./report.json
    node ./test/index.js

    mkdir integration_output
    cp ./cucumber_report.html integration_output/apickli_report.html 
  displayName: runApickli
  enabled: "true"

# Publish integration test folder result
- task: PublishBuildArtifacts@1
  displayName: publishInteegrationTestsResults
  enabled: "true"
  inputs:
    pathToPublish: integration_output
    artifactName: integration-tests


